// Generated by AIG Copilot - start
// Generated by AIG Copilot
import { Component } from '@angular/core';
import { HeaderComponent } from '../shared/header.component';

@Component({
  selector: 'app-notification',
  standalone: true,
  imports: [HeaderComponent],
  templateUrl: './notification.component.html',
  styleUrls: ['./notification.component.css'],
})
export class NotificationComponent {
  logout() {
    window.location.href = '/';
  }
}
// Generated by AIG Copilot - end
