// Generated by AIG Copilot - start
import { Component } from '@angular/core';
import { HeaderComponent } from '../shared/header.component';
import { AuthService } from '../auth/auth.service';
import { Router, ActivatedRoute } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
@Component({
  selector: 'app-claims',
  standalone: true,
  imports: [HeaderComponent, CommonModule, FormsModule],
  templateUrl: './claims.component.html',
  styleUrls: ['./claims.component.css'],
})
export class ClaimsComponent {
  // Generated by AIG Copilot - start
  showNewClaimForm = false;

  newClaim = {
    policyId: '',
    type: '',
    amount: '',
    date: '',
    remarks: '',
  };

  onCancelNewClaim() {
    this.showNewClaimForm = false;
    this.newClaim = {
      policyId: '',
      type: '',
      amount: '',
      date: '',
      remarks: '',
    };
  }

  onSubmitNewClaim() {
    // Here you would call a service to submit the claim
    alert('Claim submitted!\n' + JSON.stringify(this.newClaim, null, 2));
    this.showNewClaimForm = false;
    this.newClaim = {
      policyId: '',
      type: '',
      amount: '',
      date: '',
      remarks: '',
    };
  }
  // Generated by AIG Copilot - end
  constructor(
    private readonly auth: AuthService,
    private readonly router: Router,
    private readonly route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    if (!this.auth.isAuthenticated()) {
      this.router.navigate(['/']);
      return;
    }
    this.route.paramMap.subscribe((params) => {
      const policyId = params.get('policyId');
      if (policyId) {
        this.showNewClaimForm = true;
        this.newClaim = {
          policyId,
          type: 'Medical',
          amount: '50000',
          date: '2025-07-15',
          remarks: 'Accident - demo data',
        };
      }
    });
  }
  logout() {
    window.location.href = '/';
  }
  onFileNewClaim() {
    this.showNewClaimForm = true;
  }
  onBackToDashboard() {
    this.router.navigate(['/dashboard']);
  }
}
// Generated by AIG Copilot - end
