// Generated by AIG Copilot - start
// Generated by AIG Copilot
import { Component } from '@angular/core';
import { HeaderComponent } from '../shared/header.component';
import { AuthService } from '../auth/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-self-service',
  standalone: true,
  imports: [HeaderComponent],
  templateUrl: './self-service.component.html',
  styleUrls: ['./self-service.component.css'],
})
export class SelfServiceComponent {
  constructor(private auth: AuthService, private router: Router) {
    if (!this.auth.isAuthenticated()) {
      this.router.navigate(['/']);
    }
  }
  logout() {
    window.location.href = '/';
  }
}
// Generated by AIG Copilot - end
