// Generated by AIG Copilot - start
// Generated by AIG Copilot
import { Component } from '@angular/core';
import { HeaderComponent } from '../shared/header.component';

@Component({
  selector: 'app-self-service',
  standalone: true,
  imports: [HeaderComponent],
  templateUrl: './self-service.component.html',
  styleUrls: ['./self-service.component.css'],
})
export class SelfServiceComponent {
  logout() {
    window.location.href = '/';
  }
}
// Generated by AIG Copilot - end
