import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import { environment } from '../../environments/environment';

@Injectable()
export class AuthService {
  // Replace with Okta app settings
  private clientId = environment.auth.clientId;
  private issuer = environment.auth.issuer;
  private redirectUri = environment.auth.redirectUri;
  private scope = environment.auth.scope;
  private codeVerifier: string | null = null;

  constructor(private router: Router) {}

  // PKCE utilities
  private base64URLEncode(str: ArrayBuffer): string {
    return btoa(String.fromCharCode(...new Uint8Array(str)))
      .replace(/\+/g, '-')
      .replace(/\//g, '_')
      .replace(/=+$/, '');
  }

  private async sha256(plain: string): Promise<ArrayBuffer> {
    const encoder = new TextEncoder();
    const data = encoder.encode(plain);
    return await window.crypto.subtle.digest('SHA-256', data);
  }

  async loginWithOkta() {
    // Generate PKCE code verifier and challenge
    this.codeVerifier = this.base64URLEncode(
      window.crypto.getRandomValues(new Uint8Array(32))
    );
    sessionStorage.setItem('pkce_code_verifier', this.codeVerifier);
    const codeChallenge = this.base64URLEncode(
      await this.sha256(this.codeVerifier)
    );
    const params = [
      `client_id=${this.clientId}`,
      `redirect_uri=${encodeURIComponent(this.redirectUri)}`,
      `response_type=code`,
      `scope=${encodeURIComponent(this.scope)}`,
      `state=STATE`,
      `nonce=NONCE`,
      `code_challenge=${codeChallenge}`,
      `code_challenge_method=S256`,
    ].join('&');
    window.location.href = `${this.issuer}/v1/authorize?${params}`;
  }

  async handleAuthCallback(queryParams: any) {
    const code = queryParams['code'];
    const codeVerifier = sessionStorage.getItem('pkce_code_verifier');
    if (!code || !codeVerifier) {
      this.router.navigate(['/']);
      return;
    }
    // Exchange code for tokens (no client secret, PKCE used)
    const body = new URLSearchParams({
      grant_type: 'authorization_code',
      client_id: this.clientId,
      redirect_uri: this.redirectUri,
      code: code,
      code_verifier: codeVerifier,
    });
    const response = await fetch(`${this.issuer}/oauth/token`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: body.toString(),
    });
    if (response.ok) {
      const tokens = await response.json();
      sessionStorage.setItem('access_token', tokens.access_token);
      sessionStorage.setItem('id_token', tokens.id_token);
      // Use Angular router for a smoother transition
      this.router.navigate(['/dashboard']);
    } else {
      this.router.navigate(['/']);
    }
  }

  getAccessToken(): string | null {
    return sessionStorage.getItem('access_token');
  }

  logout() {
    const idToken = sessionStorage.getItem('id_token'); // Generated by AIG Copilot
    sessionStorage.clear();
    window.location.href = `${
      this.issuer
    }/v1/logout?id_token_hint=${idToken}&post_logout_redirect_uri=${encodeURIComponent(
      'http://localhost:4200/'
    )}`;
  }

  isAuthenticated(): boolean {
    return !!this.getAccessToken();
  }

  // Generated by AIG Copilot
  /**
   * Returns the user's name from the id_token (JWT) if available.
   */
  getUserName(): string | null {
    const idToken = sessionStorage.getItem('id_token');
    if (!idToken) return null;
    // JWT: header.payload.signature
    const payload = idToken.split('.')[1];
    if (!payload) return null;
    try {
      const decoded = JSON.parse(
        atob(payload.replace(/-/g, '+').replace(/_/g, '/'))
      );
      return decoded.name || decoded.nickname || decoded.email || null;
    } catch {
      return null;
    }
  }

  /**
   * Returns the expiration time (exp claim) of the id_token as a Date, or null if not available.
   */
  getIdTokenExpiry(): Date | null {
    const idToken = sessionStorage.getItem('id_token');
    if (!idToken) return null;
    const payload = idToken.split('.')[1];
    if (!payload) return null;
    try {
      const decoded = JSON.parse(
        atob(payload.replace(/-/g, '+').replace(/_/g, '/'))
      );
      if (decoded.exp) {
        return new Date(decoded.exp * 1000);
      }
    } catch {
      return null;
    }
    return null;
  }

  /**
   * Checks if the id_token is expired.
   */
  isIdTokenExpired(): boolean {
    const expiry = this.getIdTokenExpiry();
    if (!expiry) return true;
    return expiry.getTime() < Date.now();
  }

  /**
   * Attempts silent renewal of tokens if expired (by redirecting to login with prompt=none).
   */
  async trySilentRenewal(): Promise<boolean> {
    if (!this.isIdTokenExpired()) return true;
    // Try silent auth (prompt=none)
    const codeVerifier =
      this.codeVerifier || sessionStorage.getItem('pkce_code_verifier');
    if (!codeVerifier) return false;
    const codeChallenge = this.base64URLEncode(await this.sha256(codeVerifier));
    const params = [
      `client_id=${this.clientId}`,
      `redirect_uri=${encodeURIComponent(this.redirectUri)}`,
      `response_type=code`,
      `scope=${encodeURIComponent(this.scope)}`,
      `state=STATE`,
      `nonce=NONCE`,
      `code_challenge=${codeChallenge}`,
      `code_challenge_method=S256`,
      `prompt=none`,
    ].join('&');
    window.location.href = `${this.issuer}/v1/authorize?${params}`;
    return false; // Will redirect
  }
}
