// Generated by AIG Copilot - start
import { Component } from '@angular/core';
import { HeaderComponent } from '../shared/header.component';
@Component({
  selector: 'app-download',
  standalone: true,
  imports: [HeaderComponent],
  templateUrl: './download.component.html',
  styleUrls: ['./download.component.css'],
})
export class DownloadComponent {
  logout() {
    // Add your logout logic here, or navigate to login
    window.location.href = '/';
  }
}
// Generated by AIG Copilot - end
