// Generated by AIG Copilot - start
import { Component } from '@angular/core';

@Component({
  selector: 'app-shared-footer',
  standalone: true,
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css'],
})
export class FooterComponent {}
// Generated by AIG Copilot - end
