// ...existing code...
// Generated by AIG Copilot - start
// Generated by AIG Copilot
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { AuthService } from '../auth/auth.service';

@Component({
  selector: 'app-shared-header',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent {
  onLogoutMenu() {
    this.userMenuOpen = false;
    this.logout.emit();
  }
  openUserMenu() {
    this.userMenuOpen = true;
  }
  closeUserMenu() {
    this.userMenuOpen = false;
  }
  @Input() showLogout = false;
  @Output() logout = new EventEmitter<void>();
  userName: string | null = null;
  userMenuOpen = false;

  constructor(private readonly auth: AuthService, private router: Router) {
    this.setUserName();
    window.addEventListener('storage', () => this.setUserName());
  }

  private setUserName() {
    this.userName = this.auth.getUserName();
  }

  navigateDashboard() {
    this.router.navigate(['/dashboard']);
  }

  toggleUserMenu() {
    this.userMenuOpen = !this.userMenuOpen;
  }

  goToProfile() {
    this.userMenuOpen = false;
    this.router.navigate(['/profile']);
  }

  goToSettings() {
    this.userMenuOpen = false;
    this.router.navigate(['/settings']);
  }
}
// Generated by AIG Copilot - end
