// Generated by AIG Copilot - start
// Generated by AIG Copilot
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-shared-header',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent {
  @Input() showLogout = false;
  @Output() logout = new EventEmitter<void>();
}
// Generated by AIG Copilot - end
