// Generated by AIG Copilot - start
// Generated by AIG Copilot
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AuthService } from '../auth/auth.service';

@Component({
  selector: 'app-shared-header',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent {
  @Input() showLogout = false;
  @Output() logout = new EventEmitter<void>();
  userName: string | null = null;

  constructor(private readonly auth: AuthService) {
    this.setUserName();
    window.addEventListener('storage', () => this.setUserName());
  }

  private setUserName() {
    this.userName = this.auth.getUserName();
  }
}
// Generated by AIG Copilot - end
