// Generated by AIG Copilot - start
import { Component } from '@angular/core';
import { HeaderComponent } from '../shared/header.component';
@Component({
  selector: 'app-bill',
  standalone: true,
  imports: [HeaderComponent],
  templateUrl: './bill.component.html',
  styleUrls: ['./bill.component.css'],
})
export class BillComponent {
  logout() {
    // Add your logout logic here, or navigate to login
    window.location.href = '/';
  }
}
// Generated by AIG Copilot - end
