// Generated by AIG Copilot - start
import { Component } from '@angular/core';
import { HeaderComponent } from '../shared/header.component';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../auth/auth.service';
import { Router, ActivatedRoute } from '@angular/router';
@Component({
  selector: 'app-payment',
  standalone: true,
  imports: [HeaderComponent, CommonModule, FormsModule],
  templateUrl: './payment.component.html',
  styleUrls: ['./payment.component.css'],
})
export class PaymentComponent {
  showNewPaymentForm = false;
  newPayment = {
    policyId: '',
    method: 'Credit Card',
    amount: '8000',
    date: '2025-07-15',
    remarks: 'Demo payment data',
  };
  constructor(
    private readonly auth: AuthService,
    private readonly router: Router,
    private readonly route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    if (!this.auth.isAuthenticated()) {
      this.router.navigate(['/']);
      return;
    }
    this.route.paramMap.subscribe((params) => {
      const policyId = params.get('policyId');
      if (policyId) {
        this.showNewPaymentForm = true;
        this.newPayment = {
          policyId,
          method: 'Credit Card',
          amount: '8000',
          date: '2025-07-15',
          remarks: 'Demo payment data',
        };
      }
    });
  }

  onSubmitNewPayment() {
    alert('Payment submitted!\n' + JSON.stringify(this.newPayment, null, 2));
    this.showNewPaymentForm = false;
    this.newPayment = {
      policyId: '',
      method: 'Credit Card',
      amount: '8000',
      date: '2025-07-15',
      remarks: 'Demo payment data',
    };
  }

  onCancelNewPayment() {
    this.showNewPaymentForm = false;
    this.newPayment = {
      policyId: '',
      method: 'Credit Card',
      amount: '8000',
      date: '2025-07-15',
      remarks: 'Demo payment data',
    };
  }
  logout() {
    window.location.href = '/';
  }
}
// Generated by AIG Copilot - end
