// Generated by AIG Copilot - start
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HeaderComponent } from '../shared/header.component';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [CommonModule, HeaderComponent],
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css'],
})
export class ProfileComponent {
  userInfo: any = {};

  constructor() {
    const idToken = sessionStorage.getItem('id_token');
    if (idToken) {
      try {
        const payload = JSON.parse(atob(idToken.split('.')[1]));
        this.userInfo = payload;
      } catch (e) {
        this.userInfo = { error: 'Invalid token' };
      }
    } else {
      this.userInfo = { error: 'No ID token found' };
    }
  }

  onLogout() {
    sessionStorage.clear();
    window.location.href = '/';
  }
}
// Generated by AIG Copilot - end
