// Generated by AIG Copilot - start
import { Component } from '@angular/core';
import { HeaderComponent } from '../shared/header.component';
import { AuthService } from '../auth/auth.service';
import { Router } from '@angular/router';
@Component({
  selector: 'app-insured',
  standalone: true,
  imports: [HeaderComponent],
  templateUrl: './insured.component.html',
  styleUrls: ['./insured.component.css'],
})
export class InsuredComponent {
  constructor(private auth: AuthService, private router: Router) {
    if (!this.auth.isAuthenticated()) {
      this.router.navigate(['/']);
    }
  }
  logout() {
    window.location.href = '/';
  }
}
// Generated by AIG Copilot - end
