// Generated by AIG Copilot - start
import { Component } from '@angular/core';
import { HeaderComponent } from '../shared/header.component';
import { AuthService } from '../auth/auth.service';
import { Router } from '@angular/router';
@Component({
  selector: 'app-insured',
  standalone: true,
  imports: [HeaderComponent],
  templateUrl: './insured.component.html',
  styleUrls: ['./insured.component.css'],
})
export class InsuredComponent {
  selectedBeneficiaryId: string | null = null;

  constructor(private auth: AuthService, private router: Router) {
    if (!this.auth.isAuthenticated()) {
      this.router.navigate(['/']);
    }
  }
  selectBeneficiary(beneficiaryId: string) {
    this.selectedBeneficiaryId = beneficiaryId;
  }
  logout() {
    window.location.href = '/';
  }

  // Generated by AIG Copilot
  onModifyBeneficiary() {
    if (this.selectedBeneficiaryId) {
      alert('Modify Beneficiary for ' + this.selectedBeneficiaryId);
    } else {
      alert('Please select a beneficiary first.');
    }
  }

  onModifyAddress() {
    if (this.selectedBeneficiaryId) {
      alert('Modify Address for ' + this.selectedBeneficiaryId);
    } else {
      alert('Please select a beneficiary first.');
    }
  }
}
// Generated by AIG Copilot - end
