// Generated by AIG Copilot - start
import { Component } from '@angular/core';
import { HeaderComponent } from '../shared/header.component';
@Component({
  selector: 'app-insured',
  standalone: true,
  imports: [HeaderComponent],
  templateUrl: './insured.component.html',
  styleUrls: ['./insured.component.css'],
})
export class InsuredComponent {
  logout() {
    // Add your logout logic here, or navigate to login
    window.location.href = '/';
  }
}
// Generated by AIG Copilot - end
