// Generated by AIG Copilot - start
// Generated by AIG Copilot
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HeaderComponent } from '../shared/header.component';
import { Router } from '@angular/router';

interface Policy {
  id: number;
  name: string;
  type: string;
  status: string;
  premium: string;
}

@Component({
  selector: 'app-policy',
  standalone: true,
  imports: [CommonModule, HeaderComponent],
  templateUrl: './policy.component.html',
  styleUrls: ['./policy.component.css'],
})
export class PolicyComponent {
  policies: Policy[] = [
    {
      id: 1,
      name: '自動車保険',
      type: 'Auto',
      status: 'Active',
      premium: '¥12,000',
    },
    {
      id: 2,
      name: '火災保険',
      type: 'Fire',
      status: 'Active',
      premium: '¥8,000',
    },
    {
      id: 3,
      name: '医療保険',
      type: 'Medical',
      status: 'Expired',
      premium: '¥5,000',
    },
  ];
  selectedPolicy: Policy | null = null;

  constructor(private router: Router) {}

  selectPolicy(policy: Policy) {
    this.selectedPolicy = policy;
  }
  backToList() {
    this.selectedPolicy = null;
  }
  logout() {
    this.router.navigate(['/']);
  }
}
// Generated by AIG Copilot - end
