// Generated by AIG Copilot - start
// Generated by AIG Copilot
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HeaderComponent } from '../shared/header.component';
import { AuthService } from '../auth/auth.service';
import { Router } from '@angular/router';

interface PolicyCoverage {
  coverageId: string;
  coverageType: string;
  planCd: string;
  faceAmount: string;
  premium: string;
  beneficiaryId: string;
}

interface Policy {
  policyNumber: string;
  productName: string;
  policyType: string;
  policyStatus: string;
  standardPremium: string;
  paymentMethod: string;
  effectiveStartDT: string;
  policyRenewalStatus: string;
  policyRenewalDT: string;
  coverages: PolicyCoverage[];
}

@Component({
  selector: 'app-policy',
  standalone: true,
  imports: [CommonModule, HeaderComponent],
  templateUrl: './policy.component.html',
  styleUrls: ['./policy.component.css'],
})
// Generated by AIG Copilot
export class PolicyComponent {
  // Generated by AIG Copilot - start
  selectedRow: Policy | undefined = undefined;

  selectRow(policy: Policy): void {
    this.selectedRow = policy;
  }

  openDetails(policy: Policy): void {
    this.selectedPolicy = policy;
  }
  // Generated by AIG Copilot - end
  // Generated by AIG Copilot - start
  isSelectedPolicy(policy: Policy): boolean {
    return (
      !!this.selectedRow &&
      this.selectedRow.policyNumber === policy.policyNumber
    );
  }
  // Generated by AIG Copilot - end
  policies: Policy[] = [
    {
      policyNumber: 'POL-1001',
      productName: '自動車保険',
      policyType: 'Auto',
      policyStatus: 'Active',
      standardPremium: '¥12,000',
      paymentMethod: 'Credit Card',
      effectiveStartDT: '2024-04-01',
      policyRenewalStatus: 'Due',
      policyRenewalDT: '2025-04-01',
      coverages: [
        {
          coverageId: 'COV-001',
          coverageType: 'Collision',
          planCd: 'PLN-A',
          faceAmount: '¥1,000,000',
          premium: '¥5,000',
          beneficiaryId: 'BEN-001',
        },
        {
          coverageId: 'COV-002',
          coverageType: 'Liability',
          planCd: 'PLN-B',
          faceAmount: '¥2,000,000',
          premium: '¥7,000',
          beneficiaryId: 'BEN-002',
        },
      ],
    },
    {
      policyNumber: 'POL-1002',
      productName: '火災保険',
      policyType: 'Fire',
      policyStatus: 'Active',
      standardPremium: '¥8,000',
      paymentMethod: 'Bank Transfer',
      effectiveStartDT: '2023-10-01',
      policyRenewalStatus: 'Active',
      policyRenewalDT: '2024-10-01',
      coverages: [
        {
          coverageId: 'COV-010',
          coverageType: 'Building',
          planCd: 'PLN-C',
          faceAmount: '¥5,000,000',
          premium: '¥8,000',
          beneficiaryId: 'BEN-003',
        },
      ],
    },
    {
      policyNumber: 'POL-1003',
      productName: '医療保険',
      policyType: 'Medical',
      policyStatus: 'Expired',
      standardPremium: '¥5,000',
      paymentMethod: 'Credit Card',
      effectiveStartDT: '2022-01-01',
      policyRenewalStatus: 'Expired',
      policyRenewalDT: '2023-01-01',
      coverages: [
        {
          coverageId: 'COV-020',
          coverageType: 'Hospitalization',
          planCd: 'PLN-D',
          faceAmount: '¥500,000',
          premium: '¥5,000',
          beneficiaryId: 'BEN-004',
        },
      ],
    },
  ];
  selectedPolicy: Policy | undefined = undefined;

  constructor(
    private readonly auth: AuthService,
    private readonly router: Router
  ) {}

  ngOnInit(): void {
    if (!this.auth.isAuthenticated()) {
      this.router.navigate(['/']);
    }
  }

  selectPolicy(policy: Policy) {
    this.selectedPolicy = policy;
  }
  backToList() {
    this.selectedPolicy = undefined;
  }
  logout() {
    this.router.navigate(['/']);
  }
  renewPolicy() {
    if (this.selectedPolicy) {
      this.selectedPolicy.policyRenewalStatus = 'Active';
      // Set new renewal date to 1 year from today (for demo)
      const today = new Date();
      const nextYear = new Date(
        today.getFullYear() + 1,
        today.getMonth(),
        today.getDate()
      );
      this.selectedPolicy.policyRenewalDT = nextYear.toISOString().slice(0, 10);
      alert('Policy renewed successfully!');
    }
  }

  // Generated by AIG Copilot - start
  // Generated by AIG Copilot - start
  onClaims(): void {
    const policy = this.selectedPolicy || this.selectedRow;
    if (!policy) {
      alert('Please select a policy from the list first.');
      return;
    }
    this.router.navigate(['/claims', policy.policyNumber]);
  }
  // Generated by AIG Copilot - end
  onPayment(): void {
    const policy = this.selectedPolicy || this.selectedRow;
    if (!policy) {
      alert('Please select a policy from the list first.');
      return;
    }
    this.router.navigate(['/payment', policy.policyNumber]);
  }
  onDownload(): void {
    this.router.navigate(['/download']);
  }
  // Generated by AIG Copilot - end
}
// Generated by AIG Copilot - end
